# Stage 1: Build the binary
FROM golang:1.21 as builder
WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o git-sync ./cmd/

# Stage 2: Create the final image
FROM alpine:3.20

ARG GITSYNC_REPOSITORY_URL="" \
    GITSYNC_REPOSITORY_BRANCH="main" \
    GITSYNC_LOCAL_PATH="/git" \
    GITSYNC_INTERVAL="30s" \
    GITSYNC_HTTP_SERVER_ADDR="0.0.0.0:8080" \
    GITSYNC_HTTP_AUTH_USERNAME="" \
    GITSYNC_HTTP_AUTH_PASSWORD="" \
    GITSYNC_HTTP_AUTH_TOKEN="" \
    GITSYNC_REPOSITORY_USER="" \
    GITSYNC_REPOSITORY_TOKEN=""

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /src/git-sync /app

ENV GITSYNC_REPOSITORY_URL=${GITSYNC_REPOSITORY_URL} \
    GITSYNC_REPOSITORY_BRANCH=${GITSYNC_REPOSITORY_BRANCH} \
    GITSYNC_LOCAL_PATH=${GITSYNC_LOCAL_PATH} \
    GITSYNC_INTERVAL=${GITSYNC_INTERVAL} \
    GITSYNC_HTTP_SERVER_ADDR=${GITSYNC_HTTP_SERVER_ADDR} \
    GITSYNC_HTTP_AUTH_USERNAME=${GITSYNC_HTTP_AUTH_USERNAME} \
    GITSYNC_HTTP_AUTH_PASSWORD=${GITSYNC_HTTP_AUTH_PASSWORD} \
    GITSYNC_HTTP_AUTH_TOKEN=${GITSYNC_HTTP_AUTH_TOKEN} \
    GITSYNC_REPOSITORY_USER=${GITSYNC_REPOSITORY_USER} \
    GITSYNC_REPOSITORY_TOKEN=${GITSYNC_REPOSITORY_TOKEN}

VOLUME ["/git"]

ENTRYPOINT ["/app/git-sync"]
