# This is a basic workflow to help you get started with Actions

name: CI-demo

on:
  push:
    branches: [ "develop-action" ]
  pull_request:
    branches: [ "develop-action" ]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.21'

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Run tests
    - name: Run tests
      run: go test -cover ./...

    # Build for Linux
    - name: Build for Linux
      run: |
        mkdir -p build/linux
        GOOS=linux GOARCH=amd64 go build -o build/linux/git-sync ./cmd/

    # Build for Windows
    - name: Build for Windows
      run: |
        mkdir -p build/windows
        GOOS=windows GOARCH=amd64 go build -o build/windows/git-sync.exe ./cmd/

    # Build for macOS
    - name: Build for macOS
      run: |
        mkdir -p build/macos
        GOOS=darwin GOARCH=amd64 go build -o build/macos/git-sync ./cmd/
        
    # Upload artifacts
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-sync-linux-amd64
        path: build/linux/git-sync

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-sync-windows-amd64
        path: build/windows/git-sync.exe

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: git-sync-macos-amd64
        path: build/macos/git-sync
