# This is a basic workflow to help you get started with Actions

name: CI-demo

on:
  push:
    branches: [ "develop-action" ]
  pull_request:
    branches: [ "develop-action" ]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      REPO_NAME: your-docker-repo-name

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Run tests
    - name: Run tests
      run: go test -cover ./...

    # Build for Linux
    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/linux/gitsync ./...

    # Build for Windows
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o build/windows/gitsync.exe ./...

    # Package application for Linux
    - name: Package for Linux
      run: |
        tar -czvf build/linux/gitsync-linux.tar.gz -C build/linux gitsync

    # Package application for Windows
    - name: Package for Windows
      run: |
        zip -j build/windows/gitsync-win64.zip build/windows/gitsync.exe

    # Upload Linux artifact
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitsync-linux
        path: build/linux/gitsync-linux.tar.gz

    # Upload Windows artifact
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitsync-win64
        path: build/windows/gitsync-win64.zip
