name: Common Actions

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.21'

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test -cover ./...
