name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/common.yml

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.21'

      # Build for Linux x64
      - name: Build for Linux x64
        run: |
          mkdir -p build/linux/x64
          GOOS=linux GOARCH=amd64 go build -o build/linux/x64/git-sync ./cmd/

      # Build for Windows x64
      - name: Build for Windows x64
        run: |
          mkdir -p build/windows/x64
          GOOS=windows GOARCH=amd64 go build -o build/windows/x64/git-sync.exe ./cmd/

      # Build for OSX x64
      - name: Build for OSX x64
        run: |
          mkdir -p build/macos
          GOOS=darwin GOARCH=amd64 go build -o build/osx/x64/git-sync ./cmd/

      # Extract release notes from CHANGELOG.md
      - name: Extract release notes
        id: extract_release_notes
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          awk '/## \['"$VERSION"'\]/,/^$/' CHANGELOG.md > release_notes.md

      # Create a new release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Upload Linux x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-linux-amd64
          path: build/linux/x64/git-sync

      - name: Upload Windows x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-windows-amd64
          path: build/windows/x64/git-sync.exe

      - name: Upload OSX x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-osx-amd64
          path: build/osx/x64/git-sync
      
      # Docker release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login docker registry
      - name: Log in to Docker Hub
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            xt10r/git-sync:latest
            xt10r/git-sync:${{ github.ref_name }}

      # Clean Docker images
      - name: Clean up
        run: |
          docker image prune -f
