name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.21'

      # Create a new release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Linux x64 artifact
      - name: Upload Linux x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-linux-amd64
          path: build/linux/x64/git-sync

      - name: Upload Windows x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-windows-amd64
          path: build/windows/x64/git-sync.exe

      - name: Upload OSX x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-sync-osx-amd64
          path: build/osx/x64/git-sync
